### ISSUE TITLE
Clockify not working and showing python error

### ISSUE THREAD

**Issue by PNeelkanth16** [ynput/ayon-clockify#1]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

### Description

I want to start timer for clockify from my launcher app but it shows error in the console.

### Version
0.2.1 Clockify addon version

### What platform were you running when you found the bug?
Windows

### Relevant log output:

```shell
▄██▄
         ▄███▄ ▀██▄ ▀██▀ ▄██▀ ▄██▀▀▀██▄    ▀███▄      █▄
        ▄▄ ▀██▄  ▀██▄  ▄██▀ ██▀      ▀██▄  ▄  ▀██▄    ███
       ▄██▀  ██▄   ▀ ▄▄ ▀  ██         ▄██  ███  ▀██▄  ███
      ▄██▀    ▀██▄   ██    ▀██▄      ▄██▀  ███    ▀██ ▀█▀
     ▄██▀      ▀██▄  ▀█      ▀██▄▄▄▄██▀    █▀      ▀██▄

     ·  · - =[ by YNPUT ]:[ http://ayon.ynput.io ]= - ·  ·

Module `blessed` failed on import or terminal creation. AYON terminal won't use colors.
>>> [ Starting WebServer server ] 
------------------+-------+--------------+---------+---------------+---------+------------+-----
Addon name        |Version|Initialization|Tray init|Connect modules|Tray menu|Addons start|Total
------------------+-------+--------------+---------+---------------+---------+------------+-----
aftereffects      |0.2.4  |0.001         |N/A      |0.000          |N/A      |N/A         |0.001
applications      |1.0.2  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
ayon_ocio         |1.1.1  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
ayon_third_party  |1.1.1  |0.000         |0.000    |0.000          |0.000    |0.036       |0.036
blender           |0.2.5  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
celaction         |0.2.0  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
cinema4d          |0.1.1  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
clockify          |0.2.1  |0.000         |1.076    |0.000          |0.002    |0.000       |1.078
deadline          |0.3.2  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
equalizer         |0.1.0  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
flame             |0.2.4  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
fusion            |0.2.1  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
hiero             |0.2.3  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
houdini           |0.3.15 |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
launcher_tool     |1.0.0  |0.000         |0.056    |0.000          |0.000    |0.000       |0.056
loader_tool       |1.0.0  |0.000         |0.045    |0.000          |0.000    |0.000       |0.045
max               |0.2.4  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
maya              |0.3.1  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
motionbuilder     |0.1.1  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
nuke              |0.2.5  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
openrv            |1.0.1  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
photoshop         |0.2.3  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
python_interpreter|1.0.0  |0.000         |0.010    |0.000          |0.000    |0.000       |0.010
resolve           |0.3.0  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
sitesync          |1.2.1  |0.000         |0.494    |0.000          |0.000    |0.001       |0.495
slack             |1.1.2  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
substancepainter  |0.2.2  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
timers_manager    |0.2.0  |0.000         |0.019    |0.000          |0.008    |0.000       |0.027
traypublisher     |0.2.7  |0.000         |0.000    |0.000          |0.000    |0.000       |0.000
tvpaint           |0.2.4  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
unreal            |0.2.4  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
zbrush            |0.3.0  |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
------------------+-------+--------------+---------+---------------+---------+------------+-----
Total             |(32)   |0.001         |1.699    |0.000          |0.010    |0.037       |1.747

*** WRN: >>> { ActionsModel }: [ Action trigger failed. ] 
==============================
argument of type 'NoneType' is not iterable
==============================
Traceback (most recent call last):
  File "C:\Users\uname\AppData\Local\Ynput\AYON\addons\core_1.0.3\ayon_core\tools\launcher\models\actions.py", line 405, in trigger_action
    action.process(selection)
  File "C:\Users\uname\AppData\Local\Ynput\AYON\addons\clockify_0.2.1\ayon_clockify\launcher_actions\ClockifyStart.py", line 37, in process
    project_id = self.clockify_api.get_project_id(
  File "C:\Users\uname\AppData\Local\Ynput\AYON\addons\clockify_0.2.1\ayon_clockify\clockify_api.py", line 206, in get_project_id
    if project_name not in all_projects:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by BigRoy** [comment]
Did you configure the correct clockify workspace id?
It may be failing to query the relevant project lists from clockify here: https://github.com/ynput/ayon-clockify/blob/develop/client/ayon_clockify/clockify_api.py#L151-L160

**Comment by PNeelkanth16** [comment]
@BigRoy
Could you help that how to properly configure clockify for ayon as I am newbie for both the application.
